### ISSUE TITLE
Klassendiagramm

### ISSUE THREAD

**Issue by maxjava44** [maxjava44/TheLegendOfPeter#5]
Ich würde die ganzen Sachen gerne auf GitHub sammeln

**Comment by maxjava44** [comment]
![Klassendiagramm1](https://user-images.githubusercontent.com/16259981/72661995-84ffc180-39e1-11ea-9c6b-dda30d92c758.jpeg)

**Comment by PeterB2020** [comment]
Du kannst doch das hier durch das Neue ersetzen?

**Comment by PeterB2020** [comment]
![spielprojekt(3)](https://user-images.githubusercontent.com/59706391/73336548-65368c00-4272-11ea-87e6-2225de17b43b.jpeg)
