### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by liwikiwi** [maxjava44/TheLegendOfPeter#7]
Hier findet ihr Designs für das Game

**Comment by liwikiwi** [comment]
Das sind die vorläufigen Designs, werden im Laufe der Zeit natürlich noch verbessert
![PeterR](https://user-images.githubusercontent.com/59730666/73336580-7d0e1000-4272-11ea-8e3c-cd56c649e6d0.png)

(blaue Augen sind gruselig)
du auch

**Comment by liwikiwi** [comment]
und noch lustige gifs 'cause why not
![llama](https://user-images.githubusercontent.com/59730666/73336667-b34b8f80-4272-11ea-9949-9a602b0b6468.gif)
![Megaman moving](https://user-images.githubusercontent.com/59730666/73336668-b47cbc80-4272-11ea-99d5-9040387e6fb0.gif)

**Comment by maxjava44** [comment]
![background](https://user-images.githubusercontent.com/16259981/74592145-a5da2780-501e-11ea-9ef0-e30e39b215d3.png)
Ich hab mal nen experimentellen Hintergrund gemacht um das Hintergrund Handling zu programmieren

**Comment by PeterB2020** [comment]
Alle Designs da
